#!/usr/bin/env python3
"""
sim_audio_publisher.py
======================
Simulated drop-in replacement for uma16_audio_publisher.

Loads a pre-generated audio field (.npz produced by audio_field_builder) and
publishes interpolated audio on uma16/audio at the same rate and with the same
Float32MultiArray layout as the real UMA-16 publisher.

The field is generated by audio_field_builder from a JSON sound-sources file.
Each source defines one or more frequency bands with independent intensities;
contributions are attenuated by inverse-square law from each source position.

Interpolation
-------------
At each tick the node looks up the robot position via the ground-truth odometry
topic (nav_msgs/Odometry), finds the K nearest field probes by XY distance, and
blends their mono waveforms with inverse-distance weighting (p=2).

Parameters
----------
  field_path            Path to the .npz file produced by audio_field_builder (required).
  ground_truth_topic    Ground-truth odometry topic.  Default: /ground_truth/M3Pro/odom
  samplerate            Must match the field.  Default: 48000
  chunk_size            Samples per published message.  Default: 8192
  channels              Output channels (broadcast).    Default: 16
  k_neighbours          IDW neighbour count.   Default: 4
  idw_power             IDW exponent.          Default: 2.0
  publish_rate          Override publish Hz. 0 = derive from samplerate/chunk_size.

Usage
-----
  # 1. Generate the field from a sound-sources JSON:
  ros2 run sim_audio audio_field_builder --sources scene.json --output /tmp/field

  # 2. Launch the publisher:
  ros2 run sim_audio sim_audio_publisher \\
      --ros-args -p field_path:=/tmp/field.npz
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import rclpy
import rclpy.executors
from nav_msgs.msg import Odometry
from rclpy.node import Node
from std_msgs.msg import Float32MultiArray, MultiArrayDimension

try:
    from scipy.spatial import KDTree
except ImportError:
    KDTree = None


class SimAudioPublisher(Node):
    def __init__(self):
        super().__init__('sim_audio_publisher')

        # --- Parameters ---
        self.declare_parameter('field_path', '')
        self.declare_parameter('ground_truth_topic', '/ground_truth/M3Pro/odom')
        self.declare_parameter('samplerate', 48000)
        self.declare_parameter('chunk_size', 8192)
        self.declare_parameter('channels', 16)
        self.declare_parameter('k_neighbours', 4)
        self.declare_parameter('idw_power', 2.0)
        self.declare_parameter('publish_rate', 0.0)  # 0 = auto

        field_path        = self.get_parameter('field_path').value
        gt_topic          = self.get_parameter('ground_truth_topic').value
        self.samplerate   = self.get_parameter('samplerate').value
        self.chunk_size   = self.get_parameter('chunk_size').value
        self.channels     = self.get_parameter('channels').value
        self.k            = self.get_parameter('k_neighbours').value
        self.idw_power    = self.get_parameter('idw_power').value
        publish_rate      = self.get_parameter('publish_rate').value

        # --- Load field ---
        if not field_path:
            self.get_logger().fatal("Parameter 'field_path' is required.")
            raise RuntimeError("field_path not set")

        self._load_field(Path(field_path))

        # --- Ground-truth position ---
        # Populated by the odometry subscriber; None until first message arrives.
        self._last_xy: np.ndarray | None = None
        self.create_subscription(Odometry, gt_topic, self._gt_odom_cb, 10)

        # --- Phase state ---
        # Running waveform loop offset, advanced each publish tick.
        self._phase_offset: int = 0

        # --- Publisher ---
        self._pub = self.create_publisher(Float32MultiArray, 'uma16/audio', 10)

        # --- Timer ---
        rate = publish_rate if publish_rate > 0.0 else self.samplerate / self.chunk_size
        period = 1.0 / rate
        self._timer = self.create_timer(period, self._publish_tick)

        self.get_logger().info(
            f"sim_audio_publisher ready — {len(self._points)} field points, "
            f"K={self.k}, IDW p={self.idw_power}, "
            f"publishing {rate:.2f} Hz on uma16/audio  "
            f"(ground truth: {gt_topic})"
        )

    # ------------------------------------------------------------------
    # Field loading
    # ------------------------------------------------------------------

    def _load_field(self, path: Path) -> None:
        if not path.exists():
            self.get_logger().fatal(f"Field file not found: {path}")
            raise FileNotFoundError(str(path))

        self.get_logger().info(f"Loading audio field: {path} …")
        data = np.load(path)

        self._points    = data['points'].astype(np.float32)    # [N, 3]
        raw_waveforms   = data['waveforms'].astype(np.float32)

        self._waveforms = raw_waveforms            # [N, seq_len]

        n_points, self._seq_len = self._waveforms.shape

        if self._seq_len < self.chunk_size:
            self.get_logger().warn(
                f"Field seq_len={self._seq_len} < chunk_size={self.chunk_size}. "
                "The sequence is shorter than one publish chunk; it will repeat "
                "within each message."
            )

        # Build KD-tree on XY only (Z is fixed height; robot moves in XY)
        if KDTree is None:
            self.get_logger().warn(
                "scipy not found. Falling back to brute-force nearest-neighbour. "
                "Install scipy for better performance: pip3 install scipy"
            )
            self._kdtree = None
        else:
            self._kdtree = KDTree(self._points[:, :2])

        self.get_logger().info(
            f"Field loaded: {n_points} points, "
            f"seq_len={self._seq_len} samples "
            f"({self._seq_len / self.samplerate * 1000:.0f} ms), "
            f"{self._waveforms.nbytes / 1024 / 1024:.1f} MiB"
        )

    # ------------------------------------------------------------------
    # Ground-truth odometry callback
    # ------------------------------------------------------------------

    def _gt_odom_cb(self, msg: Odometry) -> None:
        """Cache the XY position from the ground-truth odometry message."""
        p = msg.pose.pose.position
        self._last_xy = np.array([p.x, p.y], dtype=np.float32)


    # ------------------------------------------------------------------
    # IDW interpolation
    # ------------------------------------------------------------------

    def _interpolate(self, xy: np.ndarray) -> np.ndarray:
        """Return [seq_len] mono waveform at XY via IDW over K nearest points."""
        k = min(self.k, len(self._points))

        if self._kdtree is not None:
            dists, idxs = self._kdtree.query(xy, k=k)
        else:
            all_dists = np.linalg.norm(self._points[:, :2] - xy, axis=1)
            idxs = np.argpartition(all_dists, k - 1)[:k]
            dists = all_dists[idxs]

        # Nearest-neighbour shortcut: exactly on a grid point
        if dists[0] < 1e-6:
            return self._waveforms[idxs[0]]  # [seq_len]

        # IDW weights: w_i = 1 / d_i^p, normalised
        weights = 1.0 / np.power(dists, self.idw_power)
        weights /= weights.sum()

        # Weighted sum: [k, seq_len] -> [seq_len]
        neighbours = self._waveforms[idxs]   # [k, seq_len]
        return (weights.astype(np.float32) @ neighbours)  # [seq_len]

    # ------------------------------------------------------------------
    # Publish tick
    # ------------------------------------------------------------------

    def _publish_tick(self) -> None:
        xy = self._last_xy

        if xy is None:
            self.get_logger().warn(
                "Ground-truth odometry not yet received; "
                "waiting before publishing.",
                throttle_duration_sec=5.0,
            )
            return

        # Interpolate full mono sequence at current position
        mono_seq = self._interpolate(xy)  # [seq_len]

        # Sliding window: extract chunk_size samples starting at _phase_offset, wrapping around the sequence boundary if needed.
        start = self._phase_offset
        end   = start + self.chunk_size

        if end <= self._seq_len:
            mono_chunk = mono_seq[start:end]
        else:
            # Wrap: tail of sequence + head of sequence
            tail = mono_seq[start:]
            head = mono_seq[:end - self._seq_len]
            mono_chunk = np.concatenate([tail, head])

        # Advance phase; wrap within seq_len
        self._phase_offset = (self._phase_offset + self.chunk_size) % self._seq_len

        # Broadcast mono chunk to all output channels: [chunk_size] -> [chunk_size, channels]
        chunk = np.broadcast_to(
            mono_chunk[:, np.newaxis],
            (self.chunk_size, self.channels),
        ).astype(np.float32)

        # Build and publish — same Float32MultiArray layout as uma16_audio_publisher
        msg = Float32MultiArray()
        msg.layout.dim = [
            MultiArrayDimension(
                label='frames',
                size=self.chunk_size,
                stride=self.chunk_size * self.channels,
            ),
            MultiArrayDimension(
                label='channels',
                size=self.channels,
                stride=self.channels,
            ),
        ]
        msg.data = chunk.flatten().tolist()
        self._pub.publish(msg)


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main(args=None) -> None:
    rclpy.init(args=args)
    try:
        node = SimAudioPublisher()
    except (RuntimeError, FileNotFoundError) as e:
        print(f"[sim_audio_publisher] Fatal: {e}", file=sys.stderr)
        rclpy.shutdown()
        return

    try:
        rclpy.spin(node)
    except (KeyboardInterrupt, rclpy.executors.ExternalShutdownException):
        pass
    finally:
        node.destroy_node()
        if rclpy.ok():
            rclpy.shutdown()


if __name__ == '__main__':
    main()
