#!/usr/bin/env python3
"""
view_audio_field.py
===================
Interactive 2-D viewer for audio fields generated by audio_field_builder.

Layout
------
  Left column  : 2-D heatmap of the grid — colour encodes the selected metric.
                 Source positions are overlaid as markers (when metadata is available).
  Right column : Inspector for the grid point nearest to the last click.
                 Top    — FFT magnitude spectrum (dB)
                 Bottom — Waveform excerpt (first 2048 samples)

Heatmap metrics (selectable via radio buttons)
-----------------------------------------------
  RMS amplitude       Overall energy at each point.
  Peak amplitude      Absolute peak of the stored waveform.
  Spectral centroid   Frequency centre-of-mass — high value = bright/treble.
  Dominant frequency  Frequency bin with the highest FFT magnitude.

Interaction
-----------
  Click any cell on the heatmap to inspect that grid point.
  The nearest grid point is highlighted and its spectrum / waveform are shown.

Usage
-----
  python3 -m sim_audio.view_audio_field  field.npz
  python3 -m sim_audio.view_audio_field  field.npz  --samplerate 48000
  ros2 run sim_audio view_audio_field    field.npz

  Metadata JSON (<stem>_metadata.json) is loaded automatically when present.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from matplotlib.widgets import RadioButtons


# ---------------------------------------------------------------------------
# Metrics
# ---------------------------------------------------------------------------

def _rms(waveforms: np.ndarray) -> np.ndarray:
    """RMS amplitude per point [N]."""
    return np.sqrt(np.mean(waveforms.astype(np.float64) ** 2, axis=1)).astype(np.float32)


def _peak(waveforms: np.ndarray) -> np.ndarray:
    """Absolute peak per point [N]."""
    return np.abs(waveforms).max(axis=1)


def _spectral_centroid(waveforms: np.ndarray, samplerate: int) -> np.ndarray:
    """Spectral centroid (Hz) per point [N]."""
    mag = np.abs(np.fft.rfft(waveforms.astype(np.float64), axis=1))  # [N, F]
    freqs = np.fft.rfftfreq(waveforms.shape[1], d=1.0 / samplerate)  # [F]
    total = mag.sum(axis=1, keepdims=True)
    total = np.where(total == 0, 1.0, total)
    centroid = (mag * freqs[np.newaxis, :]).sum(axis=1) / total[:, 0]
    return centroid.astype(np.float32)


def _dominant_freq(waveforms: np.ndarray, samplerate: int) -> np.ndarray:
    """Frequency of the strongest FFT bin per point [N]."""
    mag = np.abs(np.fft.rfft(waveforms.astype(np.float64), axis=1))
    freqs = np.fft.rfftfreq(waveforms.shape[1], d=1.0 / samplerate)
    return freqs[mag.argmax(axis=1)].astype(np.float32)


METRICS: dict[str, callable] = {
    'RMS amplitude':      lambda w, sr: _rms(w),
    'Peak amplitude':     lambda w, sr: _peak(w),
    'Spectral centroid':  _spectral_centroid,
    'Dominant frequency': _dominant_freq,
}

METRIC_UNITS: dict[str, str] = {
    'RMS amplitude':      'RMS',
    'Peak amplitude':     'Peak',
    'Spectral centroid':  'Hz',
    'Dominant frequency': 'Hz',
}


# ---------------------------------------------------------------------------
# Grid helpers
# ---------------------------------------------------------------------------

def _reshape_to_grid(values: np.ndarray,
                     points: np.ndarray) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Reshape flat [N] values to [n_y, n_x] and return (grid, xs, ys)."""
    xs = np.unique(points[:, 0])
    ys = np.unique(points[:, 1])
    n_x, n_y = len(xs), len(ys)
    # Points are in meshgrid(xs, ys) order: outer=y, inner=x
    grid = values.reshape(n_y, n_x)
    return grid, xs, ys


def _nearest_point_idx(click_x: float, click_y: float,
                       points: np.ndarray) -> int:
    """Return index of the grid point closest to (click_x, click_y)."""
    dists = (points[:, 0] - click_x) ** 2 + (points[:, 1] - click_y) ** 2
    return int(dists.argmin())


# ---------------------------------------------------------------------------
# Viewer
# ---------------------------------------------------------------------------

class AudioFieldViewer:
    def __init__(self, points: np.ndarray, waveforms: np.ndarray,
                 samplerate: int, metadata: dict | None):
        self._points    = points      # [N, 3] float32
        self._waveforms = waveforms   # [N, seq_len] float32
        self._sr        = samplerate
        self._meta      = metadata

        # Pre-compute all metrics once
        self._metric_data: dict[str, np.ndarray] = {
            name: fn(waveforms, samplerate)
            for name, fn in METRICS.items()
        }

        self._current_metric = 'RMS amplitude'
        self._selected_idx: int | None = None

        self._build_figure()

    # ------------------------------------------------------------------
    # Figure construction
    # ------------------------------------------------------------------

    def _build_figure(self) -> None:
        fig = plt.figure(figsize=(14, 7))
        fig.canvas.manager.set_window_title('Audio Field Viewer')

        # Outer split: radio buttons | heatmap | inspector
        outer = gridspec.GridSpec(
            1, 3, figure=fig,
            left=0.01, right=0.98, top=0.95, bottom=0.05,
            width_ratios=[0.14, 0.50, 0.36],
            wspace=0.05,
        )

        # Left: radio buttons
        ax_radio = fig.add_subplot(outer[0])
        ax_radio.set_axis_off()
        radio_ax = fig.add_axes([0.01, 0.30, 0.12, 0.40])
        self._radio = RadioButtons(
            radio_ax,
            list(METRICS.keys()),
            active=list(METRICS.keys()).index(self._current_metric),
        )
        self._radio.on_clicked(self._on_metric_change)
        radio_ax.set_title('Metric', fontsize=9, pad=4)

        # Centre: heatmap
        self._ax_map = fig.add_subplot(outer[1])

        # Right: inspector (spectrum top, waveform bottom)
        right = gridspec.GridSpecFromSubplotSpec(
            2, 1, subplot_spec=outer[2],
            hspace=0.45,
        )
        self._ax_spec  = fig.add_subplot(right[0])
        self._ax_wave  = fig.add_subplot(right[1])
        self._fig = fig
        self._cbar = None  # created once on first heatmap draw

        # Initial draw
        self._draw_heatmap()
        self._draw_inspector_empty()

        fig.canvas.mpl_connect('button_press_event', self._on_click)

    # ------------------------------------------------------------------
    # Heatmap
    # ------------------------------------------------------------------

    def _draw_heatmap(self) -> None:
        ax = self._ax_map
        ax.cla()

        values = self._metric_data[self._current_metric]
        grid, xs, ys = _reshape_to_grid(values, self._points)

        x_min, x_max = xs[0], xs[-1]
        y_min, y_max = ys[0], ys[-1]

        im = ax.imshow(
            grid,
            origin='lower',
            extent=[x_min, x_max, y_min, y_max],
            aspect='equal',
            cmap='plasma',
            interpolation='nearest',
        )

        # Colorbar: create once; update the mappable on subsequent draws
        if self._cbar is None:
            self._cbar = self._fig.colorbar(im, ax=ax, fraction=0.03, pad=0.02)
        else:
            self._cbar.update_normal(im)
        self._cbar.set_label(
            f"{self._current_metric} ({METRIC_UNITS[self._current_metric]})",
            fontsize=8,
        )

        # Source positions from metadata
        if self._meta and 'sources' in self._meta:
            for i, src in enumerate(self._meta['sources']):
                ax.plot(src['x'], src['y'], marker='*', color='cyan',
                        markersize=14, markeredgecolor='white', markeredgewidth=0.8,
                        zorder=5)
                ax.annotate(
                    f"S{i}",
                    xy=(src['x'], src['y']),
                    xytext=(4, 4), textcoords='offset points',
                    color='white', fontsize=8, fontweight='bold',
                    zorder=6,
                )

        # Selection marker
        if self._selected_idx is not None:
            px, py = self._points[self._selected_idx, :2]
            ax.plot(px, py, 'o', color='lime', markersize=10,
                    markeredgecolor='white', markeredgewidth=1.5, zorder=7)

        ax.set_xlabel('X (m)')
        ax.set_ylabel('Y (m)')
        ax.set_title(self._current_metric, fontsize=10)

        self._im = im
        self._fig.canvas.draw_idle()

    # ------------------------------------------------------------------
    # Inspector
    # ------------------------------------------------------------------

    def _draw_inspector_empty(self) -> None:
        for ax in (self._ax_spec, self._ax_wave):
            ax.cla()
            ax.set_facecolor('#1a1a1a')
            ax.tick_params(colors='#888888')
            for spine in ax.spines.values():
                spine.set_edgecolor('#444444')
        self._ax_spec.set_title('Click a grid point to inspect', fontsize=9, color='#aaaaaa')
        self._ax_spec.set_xlabel('Frequency (Hz)', fontsize=8)
        self._ax_spec.set_ylabel('Magnitude (dB)', fontsize=8)
        self._ax_wave.set_xlabel('Sample', fontsize=8)
        self._ax_wave.set_ylabel('Amplitude', fontsize=8)
        self._ax_wave.set_title('Waveform excerpt', fontsize=9)
        self._fig.canvas.draw_idle()

    def _draw_inspector(self, idx: int) -> None:
        px, py, pz = self._points[idx]
        waveform = self._waveforms[idx].astype(np.float64)
        seq_len  = len(waveform)

        # --- Spectrum ---
        ax = self._ax_spec
        ax.cla()
        ax.set_facecolor('#1a1a1a')

        mag   = np.abs(np.fft.rfft(waveform))
        freqs = np.fft.rfftfreq(seq_len, d=1.0 / self._sr)
        # dB, floor at -80 dB
        ref = mag.max() if mag.max() > 0 else 1.0
        db  = 20.0 * np.log10(np.maximum(mag / ref, 1e-4))

        ax.plot(freqs, db, color='#00bfff', linewidth=0.8)
        ax.fill_between(freqs, db.min(), db, alpha=0.25, color='#00bfff')
        ax.set_xlabel('Frequency (Hz)', fontsize=8)
        ax.set_ylabel('Magnitude (dB)', fontsize=8)
        ax.set_title(f'Spectrum  ({px:.1f}, {py:.1f}) m', fontsize=9)
        ax.set_ylim(bottom=-82, top=2)
        ax.axhline(-3,  color='#ffaa00', linewidth=0.6, linestyle='--', alpha=0.7)
        ax.axhline(-6,  color='#ff6600', linewidth=0.6, linestyle='--', alpha=0.5)
        ax.axhline(-20, color='#888888', linewidth=0.6, linestyle='--', alpha=0.4)
        ax.set_facecolor('#111111')
        ax.tick_params(colors='#aaaaaa', labelsize=7)
        for spine in ax.spines.values():
            spine.set_edgecolor('#444444')

        # Annotate source bands if metadata available
        if self._meta and 'sources' in self._meta:
            for src in self._meta['sources']:
                for band in src['bands']:
                    ax.axvspan(band['freq_min'], band['freq_max'],
                               alpha=0.08, color='yellow', zorder=0)

        # --- Waveform excerpt ---
        ax2 = self._ax_wave
        ax2.cla()
        excerpt_len = min(2048, seq_len)
        t_ms = np.arange(excerpt_len) / self._sr * 1000.0
        ax2.plot(t_ms, waveform[:excerpt_len], color='#7fff7f', linewidth=0.7)
        ax2.set_xlabel('Time (ms)', fontsize=8)
        ax2.set_ylabel('Amplitude', fontsize=8)
        ax2.set_title(f'Waveform (first {excerpt_len} samples)', fontsize=9)
        ax2.set_facecolor('#111111')
        ax2.tick_params(colors='#aaaaaa', labelsize=7)
        for spine in ax2.spines.values():
            spine.set_edgecolor('#444444')
        ax2.axhline(0, color='#444444', linewidth=0.5)

        self._fig.canvas.draw_idle()

    # ------------------------------------------------------------------
    # Event handlers
    # ------------------------------------------------------------------

    def _on_metric_change(self, label: str) -> None:
        self._current_metric = label
        self._draw_heatmap()

    def _on_click(self, event) -> None:
        if event.inaxes is not self._ax_map:
            return
        if event.xdata is None or event.ydata is None:
            return

        idx = _nearest_point_idx(event.xdata, event.ydata, self._points)
        self._selected_idx = idx
        self._draw_heatmap()
        self._draw_inspector(idx)

    # ------------------------------------------------------------------
    # Show
    # ------------------------------------------------------------------

    def show(self) -> None:
        plt.show()


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def _build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog='view_audio_field',
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    p.add_argument(
        'field', metavar='FIELD.npz',
        help='Path to the .npz audio field file.',
    )
    p.add_argument(
        '--samplerate', type=int, default=48000,
        help='Sample rate in Hz. Overridden automatically if metadata JSON is found. '
             'Default: 48000',
    )
    return p


def main(args=None) -> None:
    parser = _build_parser()
    ns = parser.parse_args(args)

    field_path = Path(ns.field)
    if not field_path.exists():
        print(f"ERROR: file not found: {field_path}", file=sys.stderr)
        sys.exit(1)

    # --- Load field ---
    data = np.load(field_path)
    points    = data['points'].astype(np.float32)    # [N, 3]
    waveforms = data['waveforms'].astype(np.float32)  # [N, seq_len]

    # --- Load metadata (optional) ---
    meta_path = field_path.parent / (field_path.stem + '_metadata.json')
    metadata: dict | None = None
    samplerate = ns.samplerate

    if meta_path.exists():
        with open(meta_path) as f:
            metadata = json.load(f)
        samplerate = metadata.get('audio', {}).get('samplerate', samplerate)
        print(f"Metadata loaded: {meta_path}")
    else:
        print(f"No metadata file found at {meta_path}; using --samplerate {samplerate}")

    n_points, seq_len = waveforms.shape
    print(f"Field: {n_points} points, seq_len={seq_len}, samplerate={samplerate} Hz")
    if metadata:
        g = metadata.get('grid', {})
        print(f"Grid:  {g.get('n_x')}×{g.get('n_y')}  spacing={metadata.get('bounds', {}).get('spacing', '?')} m")
        if 'sources' in metadata:
            print(f"Sources: {len(metadata['sources'])}")

    viewer = AudioFieldViewer(points, waveforms, samplerate, metadata)
    viewer.show()


if __name__ == '__main__':
    main()
