<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>uma16</name>
  <version>0.0.0</version>
  <description>Contains a number of ROS2 nodes for the UMA16v2 microphone array</description>
  <maintainer email="85761499+Sir-Kuhnhero@users.noreply.github.com">Sir Kuhnhero</maintainer>
  <license>TODO: License declaration</license>

  <depend>rclpy</depend>
  <depend>std_msgs</depend>

  <exec_depend>python3-sounddevice</exec_depend>
  <exec_depend>python3-numpy</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
